[package]
name = "monkey-interpreter"
version = "0.1.0"
authors = ["irtfrm <frm.tomoya@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
